# Site settings
name: Stay hungry, Stay foolish
email: lxyhunnu@gmail.com
author: XiLuo
url: https://github.com/LuoXiaoyi
resume_site: https://github.com/LuoXiaoyi
github: https://github.com/LuoXiaoyi
baseurl: "/blog"
description: 做一个有技术情节的码农
meta_description: 西罗;做一个有技术情节的码农;
motto: Be the best or nothing
banner: 从精于一开始

permalink: /:categories/:year/:month/:day/:title/
#permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoxiaoyi
destination: ../_site

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

